### ISSUE TITLE
Trouble with str_replace_all

### ISSUE THREAD

**Issue by eliebs** [tidyverse/stringr#144]
I would like to do multiple replacements to the same string. The following example is given in the documentation of package stringr:
x <- c("1 house", "2 cars", "3 people")
str_replace_all(x, c("1" = "one", "2" = "two", "3" = "three"))

My system replies a failure message: argument replacement is missing.
What is going wrong?

**Comment by dracodoc** [comment]
I just met the same problem. If you looked the source code, the function checked if there are only 2 parameters, i.e. `replacement` is missing. In that case it will unwrap the named vector into 2 vectors, `pattern`, `replacement`, then just call the regular 3 parameters version.

It's easier for user to write the parameters, but RStudio is checking function parameters with function signature and found mismatch. RStudio have no way to know the magic done inside the function. I don't think this warning can be removed since it's the right behavior.

In the other hand the named vector do have its convenience.  One method I can think of to solve this, is to add another function signature for 2 parameters case, 
`str_replace_all_by_pair(string, pattern_replacement_pair)`, which just do the magic then call the 3 parameters version.

It should not bring too much burden for user to remember this extra method, instead it's reasonable to separate two actual quite different use cases.

**Comment by hadley** [comment]
I don't understand the problem. It works fine for me:

``` r
library(stringr)
x <- c("1 house", "2 cars", "3 people")
str_replace_all(x, c(`1` = "one", `2` = "two", `3` = "three"))
#> [1] "one house"    "two cars"     "three people"
```

**Comment by dracodoc** [comment]
@hadley , There is no problem running the example. It's RStudio will have this warning about parameter missing.

![2017-01-08_191111_cr](https://cloud.githubusercontent.com/assets/1730496/21754831/4e660cdc-d5d6-11e6-9089-fa7b3105f907.png)

**Comment by eliebs** [comment]
Thank you for your comment.
For a moment, it seems to me that the problem comes from RStudio. But it 
is not so! In the  R GUI (version 3.0.3): I coppied your commands in my 
R console, then the same error appears as in RStudio.

**Comment by dracodoc** [comment]
What's your environment, including stringr version? I think the current stringr help actually used a different example for this usage.

**Comment by dracodoc** [comment]
I just realized the RStudio warning on function parameters is not on by default. That's why @hadley didn't see the warning. 

As for code itself, it should run without problem in both RStudio and R GUI. I never saw failure message for this. @eliebs Do you have a more strict setting for function parameters in your R environment?
