### ISSUE TITLE
Splitting string at "." is broken

### ISSUE THREAD

**Issue by Mashin6** [tidyverse/stringr#303]
str_split() returns vector of empty strings when attempting to split string at period "."

R 3.6.0
stringr 1.4.0
macOS 10.14.5

![image](https://user-images.githubusercontent.com/5265707/61680546-f6cbac80-acd7-11e9-9e4d-3978b7dc71c4.png)

**Comment by cderv** [comment]
To use `str_split`, you need to provide a pattern argument. By default, this pattern is a regular expression. 
That is why when you provide `"."`, it does not split in two parts because `"."` is a special character in a regex expression. You need to escape or use `stringr` helper like `fixed`. All this is explain in the documentation `?str_split`, I don't think this is broken. Here is an example:

``` r
library(stringr)
packageVersion("stringr")
#> [1] '1.4.0'
str_split("A.B", "\\.")
#> [[1]]
#> [1] "A" "B"
str_split("A.B", fixed("."))
#> [[1]]
#> [1] "A" "B"
str_split("A.B", coll("."))
#> [[1]]
#> [1] "A" "B"
```

<sup>Created on 2019-07-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Hope it helps.

**Comment by jxu** [comment]
This is intended. From docs

> pattern: The default interpretation is a regular expression
