### ISSUE TITLE
stringr doesn't work with current ICU release

### ISSUE THREAD

**Issue by bbo2adwuff** [tidyverse/stringr#320]
stringr doesn't work with current ICU 65 release. Related to https://github.com/tidyverse/stringr/issues/68

```r
* installing *source* package ‘stringr’ ...
** package ‘stringr’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/test/R/x86_64-pc-linux-gnu-library/3.6/stringi/libs/stringi.so':
  libicui18n.so.64: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘stringr’
* removing ‘/home/test/R/x86_64-pc-linux-gnu-library/3.6/stringr’
```

I do have icu 65.1 installed (libs can be found here: `/usr/lib/libicui18n.so.65` and `/usr/lib/libicuuc.so.65`).

**Comment by cderv** [comment]
> unable to load shared object '/home/test/R/x86_64-pc-linux-gnu-library/3.6/stringi/libs/stringi.so':

I wonder if this is not a `stringi` issue. Did you try installing `stringi` before that ? 
Does `stringi` 📦 works ? 

ICU is used in stringi and stringr depends on stringi. 
See INSTALL doc in stringi maybe: https://github.com/gagolews/stringi/blob/master/INSTALL

**Comment by bbo2adwuff** [comment]
Nice catch, I had to recompile `stringi` and now it works! Thanks!

**Comment by chendaniely** [comment]
I was having the same issue these past days and since this is one of the top google results while looking for a solution I'll elaborate on what @bbo2adwuff said.

In essesence you need to re-install `stringi` from scratch, one of the easiest ways is to uninstall the package first and then run `install.packages()` again.
I was having the same `libicui18n.so.64: cannot open shared object file` problem because arch linux updated to icu-65 mid November (last update to icu-64 was in late april). The other package updates that seemed to be affected were `tidyverse`, `knitr`, `roxygen2`, and `selectr`

Removing the packages and reinstalling it all fixed it for me

```
> remove.packages("tidyverse", lib="~/R/x86_64-pc-linux-gnu-library/3.6")
> remove.packages("knitr", lib="~/R/x86_64-pc-linux-gnu-library/3.6")
> remove.packages("roxygen2", lib="~/R/x86_64-pc-linux-gnu-library/3.6")
> remove.packages("selectr", lib="~/R/x86_64-pc-linux-gnu-library/3.6")
> remove.packages("stringi", lib="~/R/x86_64-pc-linux-gnu-library/3.6")
> remove.packages("stringr", lib="~/R/x86_64-pc-linux-gnu-library/3.6")
> install.packages(c("knitr", "roxygen2", "selectr", "selectr", "tidyverse", "stringi", "stringr"))
```

If you're on arch linux, downgrading `icu` via `sudo pacman -U /var/cache/pacman/pkg/icu-64.2-1-x86_64.pkg.tar.xz` is **not** the solution, it'll break a bunch of other things in the system (including not being able to load r and rstudio)

**Comment by gagolews** [comment]
Thanks @chendaniely for elaborating on this!

**Comment by zhenjieliang** [comment]
Thanks @chendaniely  you are wonderful!
