### ISSUE TITLE
Add whitespace_only option to str_wrap()

### ISSUE THREAD

**Issue by chris2b5** [tidyverse/stringr#335]
### Description
`str_wrap`  sometimes inserts newlines at unwanted positions. The underlying function `stringi::stri_wrap` provides an option `whitespace_only` to force it to wrap only at whitespace. Exposing this option in the interface to `str_wrap` would provide an easy way to avoid this in many cases.

### Reprex
``` r
library(stringr)
cat(str_wrap("weighted time spent doing I/Os (ms)", width = 14))
#> weighted time
#> spent doing I/
#> Os (ms)

# expected output:
cat(stringi::stri_wrap("weighted time spent doing I/Os (ms)", width = 14,
                       simplify = FALSE, whitespace_only = TRUE) %>%
      vapply(., str_c, collapse = "\n", character(1))
)
#> weighted time
#> spent doing
#> I/Os (ms)
```

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Could this just be the default?

**Comment by chris2b5** [comment]
> Could this just be the default?

Actually, yes - would be fine by me!

**Comment by francisbarton** [comment]
The `whitespace_only` parameter is just what I was looking for with a recent project - thanks!
The option is documented on the [official stringr reference site](https://stringr.tidyverse.org/reference/str_wrap.html) - which made me think I could use it already. But I am just on the CRAN version of `stringr` (1.4.0), so it's not yet available.
*Aside: I think features that are only available in the development version should be flagged as such in the docs. (Or: how do you switch between the docs for the latest release and the docs for the dev version on the tidyverse site?)*

I think I will wait for this option to reach CRAN, rather than switching to the dev version. I've used chris's `stringi` solution for now.
