### ISSUE TITLE
regular expressions vignette: 'fruit' vector not defined

### ISSUE THREAD

**Issue by david-romano** [tidyverse/stringr#348]
The object `fruit` is used several times in the vignette created from [regular-expressions.Rmd](https://github.com/tidyverse/stringr/blob/master/vignettes/regular-expressions.Rmd), but is not defined.  (I'm new to R markdown, so I don't see where the object resides so that it doesn't generate errors in the vignette.)

**Comment by rjpat** [comment]
The `fruit` dataset is stored inside the `{stringr}` package so that anytime it is loaded in the `fruits` data set is available as well. The other datasets included in `{stringr}` are sentences and words.

Can see the raw files in [this folder,](https://github.com/tidyverse/stringr/tree/master/data) and I think the code that loads them [is here](https://github.com/tidyverse/stringr/blob/master/R/data.R)

**Comment by david-romano** [comment]
Thanks for pointing this out, @rjpat.  I still think it would be helpful to make this explicit for the reader, maybe with a parenthetical comment after the first occurrence of `fruit`, along the lines of
> (Note that the vector `fruit` is made available upon loading the `stringr` package.)

**Comment by hadley** [comment]
@david-romano generally, vignettes will assume basically familiarity with R, and dataset loading is one of those things we just expect you to already know about. I know this isn't true for everyone, but I think it's the right tradeoff.

**Comment by david-romano** [comment]
Thanks -- this is helpful to know for instructing students in how to
interact with the documentation.
