### ISSUE TITLE
coll() function doesn't accept the strength argument from stri_opts_collator

### ISSUE THREAD

**Issue by jjesusfilho** [tidyverse/stringr#368]
According to the documentation, function `coll` would accept the arguments from ```stringi::stri_opts_collation```,  but it doesn't work with strength:

``` r
stringr::str_detect("Mário", stringr::coll("mario", strength = 1L))
#> Error in stri_opts_collator(strength = if (ignore_case) 2L else 3L, locale = locale, : formal argument "strength" matched by multiple actual arguments
```
But I if use stringi package, I get no error:

``` r
stringi::stri_detect_coll("Mário", "mario", strength = 1L)
#> [1] TRUE
```

<sup>Created on 2021-03-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately because it's unlikely to affect many people, we don't have the development resources to fix at this time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Comment by hadley** [comment]
Figured out a simple way to implement this, so it now works.

```R
stringr::str_detect("Mário", stringr::coll("mario", strength = 1L))
#> [1] TRUE
```
