### ISSUE TITLE
Possible unintended behaviour of invert_match

### ISSUE THREAD

**Issue by AlunHewinson** [tidyverse/stringr#50]
If you use `str_locate_all()` on a string with consecutive matches, e.g.
`str_locate_all(c("hello"), c("l"))`
and then try to `invert_match()` it, you get row of the resultant matrix which is potentially problematic:
`invert_match(str_locate_all(c("hello"), c("l"))[[1]])`
gives

```
     start end
[1,]     0   2
[2,]     4   3
[3,]     5  -1
```

That row 2 is odd: the string start at position 4 and ends at position 3.  Perhaps this behaviour is intended but perhaps not.  I would have expected the matrix to be 2x2, since there are two regions with non-matched characters, "he" and "o".  The zero-length "match" between the "l"s could be unexpected for some users.
I believe that this case should at least be addressed in the help file to manage users' expectations of how the function behaves, or possibly corrected if the function isn't intended to produce that sort of result.

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately since it doesn't seem to affect many people, and given that 7 years have elapsed since it was first filed, it's clear we don't have the development resources to fix at this time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.
