### ISSUE TITLE
Font is too big in the viewer from `str_view()` and `str_view_all()`

### ISSUE THREAD

**Issue by Fred-Wu** [tidyverse/stringr#523]
I haven't used `str_view()` for a while, and only recently realised the changes. 

The old `str_view()` prints the text nicely in the viewer automatically, but the current version prints them with large font, so that I have to maxmise the pane to see all of them in RStudio or open it in a browser. 

Also just wondering any reason for the default change of the old `str_view()`.

**Comment by hadley** [comment]
I think you must still have an old version of stringr because `str_view()` now prints in the console, not the viewer.

**Comment by lucavalery** [comment]
I think a comment here is more appropriate than opening a new issue (unless someone thinks otherwise).
 
The output of the old `str_view` was very nice not only in the viewer, but also in htmls rendered through markdown. 
Is there a way of reproducing in that setting the truly nice output of the old `str_view`:

`c("a cat", "that dog", "a similar cat", "the penguin") |> str_view("cat")`

![str_view_before](https://github.com/tidyverse/stringr/assets/27213536/8e1f2441-7179-4042-b420-da468d64a0a2)

Instead of the unformatted output of the new one:
![image](https://github.com/tidyverse/stringr/assets/27213536/18cb3de1-e09e-429d-9533-cc19672870b8)?

Thank you in advance!
