### ISSUE TITLE
SQL's LIKE is actually case sensitive

### ISSUE THREAD

**Issue by hadley** [tidyverse/stringr#543]
So need to change the default, and update the docs.

Probably worth a little exploration of impact on users (with github search for `str_like()`).

**Comment by edward-burn** [comment]
@hadley I wonder whether instead of changing the default of ignore_case, what about introducing a new function: `str_ilike()`?

Then stringr could have two functions
- str_like - similar to SQL LIKE that is case sensitive
- str_ilike - similar to SQL ILIKE that is case insensitive

I suppose the benefit of this would be that these would more directly align with SQL concepts. But the drawback would be this would be a bigger change (although perhaps a less subtle breaking change than simply switching the default)

**Comment by hadley** [comment]
Yeah, I think that's a good idea.

**Comment by edward-burn** [comment]
@hadley I have opened pr #544 with a str_ilike function and the ignore_case argument in str_like deprecated

**Comment by hadley** [comment]
Thanks, I'll take a look when I'm next working on stringr.
